site: Kenneth Chang
url: https://kennethcha.ng
title: Kenneth Chang
description: Kenneth Chang’s Personal Page
description_en: Kenneth Chang’s Personal Page
description_es: Página Personal de Kenneth Chang
description_yue: Kenneth Chang嘅個人網頁

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
  posts:
    output: true
  main:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: "_main"
    values:
      permalink: /:name

  - scope:
      path: "assets/images"
    values:
      image: true

  - scope:
      path: _posts/en
      type: posts
    values:
      lang: en
      permalink: /en/:year/:month/:day/:slug
  - scope:
      path: _posts/es
      type: posts
    values:
      lang: es
      permalink: /es/:year/:month/:day/:slug
  - scope:
      path: _posts/yue
      type: posts
    values:
      lang: yue
      permalink: /yue/:year/:month/:day/:slug

  - scope:
      path: _pages/en
      type: pages
    values:
      lang: en
      permalink: /en/:name
  - scope:
      path: _pages/es
      type: pages
    values:
      lang: es
      permalink: /es/:name
  - scope:
      path: _pages/yue
      type: pages
    values:
      lang: yue
      permalink: /yue/:name

