site: Kenneth Chang
url: https://kennethcha.ng
title: Kenneth Chang
description: Kenneth Chang’s Personal Page
description_en: Kenneth Chang’s Personal Page
description_es: Página Personal de Kenneth Chang
description_yue: Kenneth Chang嘅個人網頁

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:path/:name
  posts:
    output: true
    permalink: /:path/:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: "assets/images"
    values:
      image: true
