site: Kenneth Chang
url: https://kennethcha.ng
title: Kenneth Chang
description: Kenneth Changs Personal Page
description_en: Kenneth Chang’s Personal Page
description_es: Página Personal de Kenneth Chang
description_yue: Kenneth Chang嘅個人網頁

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: "default"
      base-url: "/"
  -
    scope:
      path: ""
      type: "pages"
    values:
      lang: "en"
      layout: "page"
      base-url: "/"
  -
    scope:
      path: ""
      type: "posts"
    values:
      lang: "en"
      layout: "post"
      base-url: "/"
  -
    scope:
      path: "en"
    values:
      lang: "en"
      base-url: "/en/"
  -
    scope:
      path: "es"
    values:
      lang: "es"
      base-url: "/es/"
  -
    scope:
      path: "yue"
    values:
      lang: "yue"
      base-url: "/yue/"
  - scope:
      path: "assets/images"
    values:
      image: true
